name = "aiovtue-blog"   # 项目名，可以改
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
SITE_URL = "https://live.yybb.us"
ADMIN_USERNAME = "Monitor"

[[d1_databases]]
binding = "DB"
database_name = "blog"
database_id = "03cdb7ac-3cae-4c3d-95da-36bf9011380a"   # 在 D1 控制台可以复制
